name: aktor
version: 0.0.1
description: A simple tool that solves Dart's lack of metaprogramming features. Perfect for building scripts, background jobs, scheduled tasks, and development utilities like code generation, data processing, and more.
repository: https://github.com/mkalmousli/aktor.dart
issue_tracker: https://github.com/mkalmousli/aktor.dart/issues
topics: [build-runner, development, codegen, metaprogramming]

environment:
  sdk: ^3.9.2

dependencies:
  analyzer: ^8.4.0
  ansi: ^0.4.2
  async: ^2.13.0
  bloc: ^9.1.0
  code_builder: ^4.11.0
  collection: ^1.19.1
  freezed_annotation: ^3.1.0
  path: ^1.9.0
  pubspec_yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.10.1
  freezed: ^3.2.3
  lints: ^6.0.0
  test: ^1.25.6

screenshots:
  - description: The aktor package logo.
    path: LogoProd.png
  