name: actor
version: 0.0.1
description: A simple tool that solves Dart's lack of metaprogramming features. Perfect for building scripts, background jobs, scheduled tasks, and development utilities like code generation, data processing, and more.
repository: https://github.com/mkalmousli/actor.dart
issue_tracker: https://github.com/mkalmousli/actor.dart/issues

environment:
  sdk: ^3.9.2

dependencies:
  analyzer:
  ansi:
  async:
  bloc:
  code_builder:
  collection:
  crypto:
  freezed_annotation:
  path: ^1.9.0
  pubspec_lock: ^3.0.2
  pubspec_yaml:
  watcher:

dev_dependencies:
  build_runner:
  freezed:
  lints: ^6.0.0
  test: ^1.25.6


screenshots:
  - description: The actor package logo.
    path: LogoProd.png